apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: default
spec:
  type: NodePort                  # Exposes service on a port on all nodes
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 8080                 # Service port inside the cluster
      targetPort: 8080           # Pod container port
      nodePort: 30090            # Node port accessible via EC2 public IP
